package com.kelsos.mbrc.enums;

import com.kelsos.mbrc.interfaces.IEventType;

public enum ModelDataEventType implements IEventType
{
	MODEL_TITLE_UPDATED,
	MODEL_ARTIST_UPDATED,
	MODEL_ALBUM_UPDATED,
	MODEL_YEAR_UPDATED,
	MODEL_VOLUME_UPDATED,
	MODEL_COVER_UPDATED,
	MODEL_COVER_NOT_FOUND,
	MODEL_CONNECTION_STATE_UPDATED,
	MODEL_REPEAT_STATE_UPDATED,
	MODEL_SHUFFLE_STATE_UPDATED,
	MODEL_SCROBBLE_STATE_UPDATED,
	MODEL_MUTE_STATE_UPDATED,
	MODEL_PLAY_STATE_UPDATED,
	MODEL_ONLINE_STATE_UPDATED,
	MODEL_LYRICS_UPDATED
}
