package com.kelsos.mbrc.enums;

import com.kelsos.mbrc.interfaces.IEventType;

public enum UserInputEventType implements IEventType
{
	USERINPUT_EVENT_REQUEST_PLAY_PAUSE,
	USERINPUT_EVENT_REQUEST_STOP,
	USERINPUT_EVENT_REQUEST_NEXT,
	USERINPUT_EVENT_REQUEST_PREVIOUS,
	USERINPUT_EVENT_REQUEST_REPEAT,
	USERINPUT_EVENT_REQUEST_SHUFFLE,
	USERINPUT_EVENT_REQUEST_LAST_FM,
	USERINPUT_EVENT_REQUEST_MUTE,
	USERINPUT_EVENT_REQUEST_LYRICS,
	USERINPUT_EVENT_REQUEST_DATA_REFRESH,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_LIST,
	USERINPUT_EVENT_REQUEST_VOLUME,
	USERINPUT_EVENT_REQUEST_PLAYBACK_POSITION,
	USERINPUT_EVENT_REQUEST_INITIALIZE,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_PLAY_NOW,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_REMOVE,
	USERINPUT_EVENT_SETTINGS_CHANGED,
	USERINPUT_EVENT_REQUEST_CONNECTION_RESET,
	USERINPUT_EVENT_CANCEL_NOTIFICATION,
    USERINPUT_EVENT_REQUEST_RATING_CHANGE,
    USERINPUT_EVENT_MOVE_NOWPLAYING_TRACK,
    USERINPUT_EVENT_LASTFM_LOVE,
    USERINPUT_EVENT_LASTFM_BAN,
    USERINPUT_EVENT_LIB_REQUEST_ALL_ARTISTS,
    USERINPUT_EVENT_LIB_REQUEST_ALL_ALBUMS,
    USERINPUT_EVENT_LIB_REQUEST_ALL_TRACKS,
    USERINPUT_EVENT_LIB_REQUEST_ALL_GENRES,
    USERINPUT_EVENT_LIB_REQUEST_SEARCH,
    USERINPUT_EVENT_LIB_REQUEST_GENRE_ARTISTS,
    USERINPUT_EVENT_LIB_REQUEST_ARTIST_ALBUMS,
    USERINPUT_EVENT_LIB_REQUEST_ALBUM_TRACKS
}
