package kelsos.mbremote.enums;

import kelsos.mbremote.Interfaces.IEventType;

public enum UserInputEventType implements IEventType
{
	USERINPUT_EVENT_REQUEST_PLAY_PAUSE,
	USERINPUT_EVENT_REQUEST_STOP,
	USERINPUT_EVENT_REQUEST_NEXT,
	USERINPUT_EVENT_REQUEST_PREVIOUS,
	USERINPUT_EVENT_REQUEST_REPEAT,
	USERINPUT_EVENT_REQUEST_SHUFFLE,
	USERINPUT_EVENT_REQUEST_LAST_FM,
	USERINPUT_EVENT_REQUEST_MUTE,
	USERINPUT_EVENT_REQUEST_LYRICS,
	USERINPUT_EVENT_REQUEST_DATA_REFRESH,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_LIST,
	USERINPUT_EVENT_REQUEST_VOLUME,
	USERINPUT_EVENT_REQUEST_PLAYBACK_POSITION,
	USERINPUT_EVENT_REQUEST_INITIALIZE,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_PLAY_NOW,
	USERINPUT_EVENT_REQUEST_NOWPLAYING_REMOVE

}
